accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('singup/', views.singup_view, name='singup'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_view, name='inndex'),
    path('<str:post_id>', views.blog_single, name='single'),
    path('category/<str:cat_name>', views.blog_category, name='blog_category'),
    path('author/<str:author_username>', views.blog_view, name='blog_author'),
    path('tag/<str:tag_name>', views.blog_view, name='blog_tag'),
    path('search/', views.blog_search, name='blog_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('website.urls', namespace='website')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('__debug__/', include(debug_toolbar.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index_view, name='home'),
    path('about/', views.index_view, name='about'),
    path('contact/', views.contect_view, name='contact'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    tags = TaggableManager(blank=True ,)
    category = models.ManyToManyField(Category)
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(null=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at',]
        # verbose_name = 'پست'
        # verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def snippets(self):
        return self.content[:200] + '...'

website/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    massage = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

website/forms.py
from django import forms
from .models import Contact
from captcha.fields import CaptchaField
class contactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def login_view(request):
    if request.method == 'POST' :
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username, password=password)
        if user is not None :
            login(request, user)
            return redirect('/')


    return render(request, 'accounts/login.html', {})

@login_required
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('/')

def singup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('accounts:login')
        form = UserCreationForm()
        context = {'form':form}
        return render(request, 'accounts/singup.html', context)
    else:
        return redirect('/')

blog/views.py
from django.shortcuts import render
from .models import Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect

# Create your views here.

def blog_view (request, **kwargs):
    posts = Post.objects.filter(status=1).order_by('-published_date')
    # if kwargs['author_username']:
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])

    try:
        posts = Paginator(posts, 2)
        page_number = request.GET.get('page')
    except PageNotAnInteger or EmptyPage:
        posts = posts.get_page(1)
    # except EmptyPage:
    #     posts = posts.get_page(1)
    posts= posts.get_page(page_number)
    content = {'posts':posts}
    return render(request, 'blog/blog-home.html',content)

def blog_single (request, post_id):
    post = Post.objects.get(pk=post_id, status=1)
    if not post.login_require :
        content = {'post':post}
        return render(request, 'blog/blog-single.html', content)
    else:
        return redirect('accounts:login')

def blog_detail (request):
    posts = Post.objects.filter(status=1)
    content = {'posts':posts}
    return render(request, 'blog/blog-home.html',content)

def blog_category(request, cat_name):
    # category = Category.objects.get(name=cat_name)
    posts= Post.objects.filter(status=1, category__name=cat_name)
    content = {'posts':posts}
    return render(request,'blog/blog-home.html', content)

def blog_search(request):
    posts= Post.objects.filter(status=1)
    if request.method=='GET':
        if s:=request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    content = {'posts':posts}
    return render(request,'blog/blog-home.html', content)

website/views.py
from django.shortcuts import render
from .forms import contactForm
from django.contrib import messages
# Create your views here.

def index_view(request):
   return render(request, 'website/index.html')

def contect_view(request):
   if request.method == 'POST':
      form = contactForm(request.POST)
      if form.is_valid():
         form.save()
         messages.add_message(request,messages.SUCCESS,'your ticket submited successfuly')
      else:
         messages.add_message(request, messages.ERROR, 'your ticket didnt submited ')
   form = contactForm()
   return render(request, 'website/contact.html', {'form':form})

templates/accounts/singup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap 5 Login form Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="vh-100 d-flex justify-content-center align-items-center bg-secondary">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="col-12 col-md-8 col-lg-6">
            <div class="card bg-white">
              <div class="card-body p-5">
                <form method="post" action="{% url 'accounts:singup' %}" class="mb-3 mt-md-4">
                    {% csrf_token %}
                  <h2 class="fw-bold mb-2 text-uppercase ">sing up</h2>
                  <p class=" mb-5">Please enter your login and password!</p>
                  <div class="mb-3">
                    <label for="username" class="form-label ">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="username">
                  </div>
                  <div class="mb-3">
                    <label for="password1" class="form-label ">Password</label>
                    <input type="password" class="form-control" name="password1" placeholder="Password">
                  </div>
                    <div class="mb-3">
                    <label for="password2" class="form-label ">confrim Password</label>
                    <input type="password" class="form-control" name="password2" placeholder="confrimPassword">
                  </div>
                  <p class="small"><a class="text-primary" href="forget-password.html">Forgot password?</a></p>
                  <div class="d-grid">
                    <button class="btn btn-outline-dark" type="submit">Login</button>
                  </div>
                </form>
                <div>
                  <p class="mb-0  text-center">Don't have an account? <a href="signup.html" class="text-primary fw-bold">Sign
                      Up</a></p>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Travel</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
		</head>
		<body>
			<header id="header">
				<div class="header-top">
					<div class="container">
			  		<div class="row align-items-center">
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
			  				<ul>
                                {% if request.user.is_authenticated %}
			  					    <li><a href="#">{{ request.user.username }}</a></li>
			  					    <li><a href="{% url 'accounts:logout' %}">logout</a></li>
                                {% else %}
                                    <li><a href="{% url 'accounts:singup' %}">singup</a></li>
			  					    <li><a href="{% url 'accounts:login' %}">login</a></li>
                                {% endif %}
			  				</ul>
			  			</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
			  		</div>
					</div>
				</div>
				<div class="container main-menu">
					<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				        <a href="index.html"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li><a href="{% url 'website:home' %}">Home</a></li>
				          <li><a href="{% url 'website:about' %}">About</a></li>
				          <li  class="menu-has-children" ><a href="{%  url 'blog:inndex' %}">Blog</a></li>
				          <li class="menu-has-children"><a href="">Pages</a>
				            <ul>
				            	  <li><a href="elements.html">Elements</a></li>
						          <li class="menu-has-children"><a href="">Level 2 </a>
						            <ul>
						              <li><a href="#">Item One</a></li>
						              <li><a href="#">Item Two</a></li>
						            </ul>
						          </li>
				            </ul>
				          </li>
				          <li><a href="{% url 'website:contact' %}">Contact</a></li>
				        </ul>
				      </nav><!-- #nav-menu-container -->
					</div>
				</div>
			</header><!-- #header -->
            {% block content %}


            {% endblock %}
            	<!-- start footer Area -->
			<footer class="footer-area section-gap">
				<div class="container">

					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="#">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="#">Blog</a></li>
											<li><a href="#">Contact</a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.
								</p>
								<div id="mc_embed_signup">
									<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscription relative">
										<div class="input-group d-flex flex-row">
											<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
										</div>
										<div class="mt-10 info"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
								</ul>
							</div>
						</div>
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
 			<script src="{% static 'js/jquery-ui.js' %}"></script>
  			<script src="{% static 'js/easing.min.js' %}"></script>
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>
			<script src="{% static 'js/mail-script.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>
		</body>
	</html>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{%  load blog_tags %}
{% block content %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
                            {% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
                                        {% for category in post.category.all %}
										<li><a href="{% url 'blog:blog_category' cat_name=category %}">{{ category.name }}</a>{% if not forloop.last %},{% endif %} </li>
                                         {% endfor %}
{#                                        <li><a href="">{{ post.category.all|join:", " }}</a></li>#}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:blog_author' author_username=post.author %}">{{ post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:'D d M Y' }}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{ post.image.url }}" alt="">
									</div>
									<a class="posts-title" href="{% url 'blog:single' post_id=post.id  %}"><h3>{{ post.title }}</h3></a>
									<p class="excert">
									{{ post.content|truncatechars:200 }}
                                    </p>
									<a href="{% url 'blog:single' post_id=post.id  %}" class="primary-btn">View More</a>
								</div>
							</div>
                            {% endfor %}
		                      {% include 'blog/include/blog-paginator.html' %}
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
                                {%  include 'blog/include/blog-search.html' %}
								<div class="single-sidebar-widget user-info-widget">
									<img src="{% static 'img/blog/user-info.png' %}" alt="">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>
								{% latestposts %}


								<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg'%}" alt=""></a>
								</div>

								{% postCategories %}

								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Architecture</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Art</a></li>
										<li><a href="#">Adventure</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Adventure</a></li>
									</ul>
								</div>								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
	{% endblock %}

templates/blog/include/blog-cat-tag.html
{% if post.tags.count > 0 %}
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:blog_tag' tag_name=tag.name  %}">{{ tag.name }}</a></li>

        {% endfor %}

    </ul>
</div>
{% endif %}

templates/blog/include/blog-popular-posts.html
{% load static %}
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
    {% for post in posts %}
<div class="single-post-list d-flex flex-row align-items-center">
    <div class="thumb">
        <img class="img-fluid" src="{{ post.image.url }}" alt="">
    </div>
    <div class="details">
        <a href="{% url 'blog:single' post_id=post.id %}"><h6>{{ post.title }}</h6></a>
{#        <p>{{ post.published_date|date:'d M Y' }}</p>#}
        <p>{{ post.published_date|naturaltime}}</p>
    </div>
</div>
        {% endfor %}
    </div>
</div>

templates/blog/include/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>

    <ul class="cat-list">
            {%for name, count in categories.items %}
        <li>
            <a href="{% url 'blog:blog_category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{ name }}</p>
                <p>{{ count }}</p>
            </a>
        </li>
				{% endfor %}
    </ul>
</div>

templates/blog/include/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:blog_search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/include/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/website/include/contact-email.html
<div class="col-lg-8">
    <form class="form-area contact-form text-right" action="{% url 'website:contact' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-6 form-group">
                <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required="" type="text">
                <input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required="" type="email">
                <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control" required="" type="text">
            </div>
            <div class="col-lg-6 form-group">
                <textarea class="common-textarea form-control" name="massage" placeholder="Enter Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea></div>
            <div class="col-lg-12">
                <div class="pb-3">
                    {{ form.captcha }}
                </div>
                <div class="alert-msg" style="text-align: left;"></div>
                <button type="submit" class="genric-btn primary" style="float: right;">Send Message</button>
            </div>
        </div>
    </form>
</div>